### ISSUE TITLE
Editor Tool doesn't parse or display content of ECF files

### ISSUE THREAD

**Issue by ZachariBarnes** [Preston-Coding/EgsEcfEditorApp#2]
Downloaded your app to see about eaiser ways to edit the files but no block information is displayed.
<img width="644" alt="image" src="https://github.com/Preston-Coding/EgsEcfEditorApp/assets/10678967/06be92a9-f780-4f25-83c8-8b8f7a75f014">
I see in your readme you had block information displaying but as you can see only Comments appear for me.
Using vanilla RE configs

Note: Same effect on Items config but Templates.ecf loads only the basic ore types (And comments)

**Comment by Ir3nicuz** [comment]
The standard setting is 25 items per page. Apperently the first 25 items of your file are simply only comments. You can switch to further pages, increase the items count per page, deactivate the comments in the filter or simply search with the filter for item/block names to find the block data.

**Comment by ZachariBarnes** [comment]
You're right of course. sorry for bothering you and thanks for the response
